name: Test Build

on:
  push:
    branches: [ main ]
    tags-ignore: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            # Workaround for npm optional dependencies bug
            # https://github.com/npm/cli/issues/4828
            rm -rf node_modules package-lock.json
            npm install
          else
            npm ci
          fi
        shell: bash

      - name: Fix Windows npm optional dependencies issue
        if: matrix.os == 'windows-latest'
        run: |
          npm install @rollup/rollup-win32-x64-msvc --save-optional

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npm run typecheck

      - name: Run tests
        run: npm run test

      - name: Build (unpacked)
        run: npm run build:unpack